# Generated by Django 4.0.3 on 2022-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
