# Generated by Django 4.0.3 on 2022-03-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Password reset')], verbose_name='Type')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('usage_date', models.DateTimeField(blank=True, null=True, verbose_name='Usage date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Confirmation token',
                'verbose_name_plural': 'Confirmation tokens',
            },
        ),
        migrations.AddConstraint(
            model_name='confirmationtoken',
            constraint=models.CheckConstraint(check=models.Q(('is_used', False), models.Q(('is_used', True), ('usage_date__isnull', False)), _connector='OR'), name='users_confirmationtoken_usage_date_is_required'),
        ),
        migrations.AlterUniqueTogether(
            name='confirmationtoken',
            unique_together={('user', 'type')},
        ),
    ]
